---
jobs:
- name: meta4
  plan:
  - get: artifact
    resource: metalink
    trigger: true
    params:
      skip_download: true
  - get: tap
  - task: update-recipe
    file: tap/ci/update-recipe-from-metalink.yml
    params:
      recipe: meta4
  - put: tap
    params:
      rebase: true
      repository: tap
- name: ssoca
  plan:
  - get: artifact
    resource: ssoca
    trigger: true
    params:
      skip_download: true
  - get: tap
  - task: update-recipe
    file: tap/ci/update-recipe-from-metalink.yml
    params:
      recipe: ssoca
  - put: tap
    params:
      rebase: true
      repository: tap
resources:
- name: tap
  type: git
  source:
    uri: git@github.com:dpb587/homebrew-tap.git
    private_key: ((tap_private_key))
    branch: master
- name: ssoca
  type: metalink-repository
  source:
    uri: git+https://github.com/dpb587/ssoca.git//ssoca-final#artifacts
- name: metalink
  type: metalink-repository
  source:
    uri: git+https://github.com/dpb587/metalink.git//stable#artifacts
resource_types:
- name: metalink-repository
  type: docker-image
  source:
    repository: dpb587/metalink-repository-resource
