name: timepolicy
permissions:
  contents: write
on:
  workflow_dispatch: {}
jobs:
  rebuild:
    name: rebuild
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: checkout-tap
      uses: actions/checkout@v3
      with:
        path: tap
    - name: checkout-resources
      uses: actions/checkout@v3
      with:
        repository: dpb587/timepolicy
        ref: resources
        path: resources
    - name: rebuild
      run: |
        cd tap
        ./scripts/rebuild-timepolicy.sh ../resources
        git add .
    - name: commit
      uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a
      with:
        commit_message: timepolicy
        repository: tap
